# Generated by Django 5.1.6 on 2025-03-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0002_driver_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='driverid',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
