# Generated by Django 5.1.6 on 2025-03-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0003_remove_login_driverid_delete_booking_delete_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='status',
        ),
    ]
