# Generated by Django 5.1.6 on 2025-03-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0004_remove_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uemail',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
